/**
 * @description This is a sample exception.
 * @usage
 *
 * You can use the exception the following way.
 * You can also take a look at {@link SampleClass} to see how it is used.
 * This is a dangerous HTML tag: <script>alert('Hello');</script>
 *
 * ```
 * try {
 *    throw new SampleException();
 * } catch (SampleException e) {
 *   System.debug('Caught exception');
 * }
 * ```
 */
public class SampleException extends Exception {}
